### ISSUE TITLE
[Enhancement] KCLVM CLI clap deps is too low and need to upgrade the clap version.

### ISSUE THREAD

**Issue by Peefy** [KusionStack/kcl#333]
## Enhancement

KCLVM CLI clap deps is too low, upgrade the version and Refactoring code in the way recommended by clap. Ref: clap-rs/clap#2835

**Comment by niconical** [comment]
I think this is a good introductory task about the [clap](https://github.com/clap-rs/clap) library, and I hope to fix it soon.

**Comment by Peefy** [comment]
> It seems to be a good introductory task about the [clap](https://github.com/clap-rs/clap) library, and I hope to fix it soon.

Thank you! I could assign this issue to U!
